[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/data/*.json"
  [headers.values]
    Cache-Control = "public, max-age=300"
